project:
  type: website
  output-dir: docs

website:
  title: "SOFT RELIC STUDIO"
  navbar:
    left:
      - href: index.qmd
        text: Gallery
      - about.qmd
      - inthemaking.qmd

format:
  html:
    lightbox: true
    theme:
      light:
        - simplex
        - custom.scss
    css: styles.css
    toc: true

editor: visual
  
# ~ additional metadata excluded for brevity ~