project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "SOFT RELIC STUDIO"
  navbar:
    left:
      - href: index.qmd
        text: Gallery
      - href: about.qmd
        text: About
      - href: inthemaking.qmd
        text: In the Making

format:
  html:
    lightbox: true
    theme:
      light:
        - simplex
        - custom.scss
    css: styles.css
    toc: true

editor: visual
  
# ~ additional metadata excluded for brevity ~