project:
  type: website
  output-dir: docs

website:
  title: "Soft Relic Studio"
  site-url: https://anorris20.github.io/Final-Project
  navbar:
    right:
      - text: Gallery
        href: index.qmd
      - text: In the Making
        href: inthemaking.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: simplex
    # comment out custom.scss if it doesnâ€™t exist
    # css: styles.css
